#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Angular-Gettext
Version  : 2.1.0.2
Release  : 3
URL      : https://pypi.python.org/packages/source/X/XStatic-Angular-Gettext/XStatic-Angular-Gettext-2.1.0.2.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-Angular-Gettext/XStatic-Angular-Gettext-2.1.0.2.tar.gz
Summary  : Angular-Gettext 2.1.0 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-Angular-Gettext-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-Angular-Gettext
--------------
Angular-Gettext javascript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Angular-Gettext package.
Group: Default
Provides: xstatic-angular-gettext-python

%description python
python components for the XStatic-Angular-Gettext package.


%prep
%setup -q -n XStatic-Angular-Gettext-2.1.0.2

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
